stages:
  - build-source
  - docker-image
#  - deploy2aws

compile:
  image: adoptopenjdk/openjdk8:latest
  stage: build-source
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/
  only:
    - tags

dockerize:
  stage: docker-image
  image: docker:git
  variables:
    GIT_STRATEGY: none
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/tony.z.1711/wapy-backend build/
    - docker tag registry.gitlab.com/tony.z.1711/wapy-backend registry.gitlab.com/tony.z.1711/wapy-backend:$CI_COMMIT_TAG
    - docker push registry.gitlab.com/tony.z.1711/wapy-backend:latest
    - docker push registry.gitlab.com/tony.z.1711/wapy-backend:$CI_COMMIT_TAG
  dependencies:
    - compile
  only:
    - tags

deploy:
  stage: deploy2aws
  image: lwolf/helm-kubectl-docker:v1103_291
  before_script:
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context $K8S_CLUSTER
  script:
    - cd k8s
    - (( echo "cat <<EOF" ; cat nbrs-backend-deployment.yml ; echo EOF ) | sh) > nbrs-backend-deployment-with-env.yml
    - kubectl apply -f nbrs-backend-deployment-with-env.yml
  only:
    - tags