FROM frolvlad/alpine-java:jdk8-slim
COPY distributions/*.zip /wapy/wapy.zip
WORKDIR /wapy
RUN ls -la
RUN unzip wapy.zip
EXPOSE 8080
WORKDIR /wapy/wapy-backend-1.0/bin/
ARG JDBC_URL
ARG JDBC_USERNAME
ARG JDBC_PASSWORD
ARG JWT_SECRET
CMD ["./me.wapy.backend"]

ENV WAPY_JDBC_URL=$JDBC_URL
ENV WAPY_JDBC_USERNAME=$JDBC_USERNAME
ENV WAPY_JDBC_PASSWORD=$JDBC_PASSWORD
ENV WAPY_JWT_SECRET=$JWT_SECRET